debug = false
addr = ":8080"
view = ["examples"]
tmp_path = "tmp"
component = ["examples"]

[iset]
acl = [["ot", "{{ if verify('@v') }}", "{{ endif }}"]]
ext = [["ot", "🤣🤣🤣", "🌹🌹🌹"], ["in", "💖💖💖💖💖", "✨✨✨✨✨"], ["as", {class = "nc"}] ]
pop = ["as", {onclick = "alert('@v')"}]

[mcss]
app = "mcss application"
